/**
 * Shared test helpers for integration tests.
 *
 * Expects a local Supabase instance running via `supabase start`.
 * Default ports: API 54321, DB 54322.
 */

// Local Supabase URLs
export const API_URL = Deno.env.get("SUPABASE_API_URL") ?? "http://127.0.0.1:54321";
export const FUNCTIONS_URL = `${API_URL}/functions/v1`;
export const REST_URL = `${API_URL}/rest/v1`;

// Local keys — set SUPABASE_ANON_KEY / SUPABASE_SERVICE_ROLE_KEY env vars,
// or the tests will use the default keys generated by `supabase start`.
// These defaults work with the standard local Supabase demo project.
export const ANON_KEY =
  Deno.env.get("SUPABASE_ANON_KEY") ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

export const SERVICE_ROLE_KEY =
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

// Default headers for PostgREST calls
export const restHeaders = {
  apikey: ANON_KEY,
  Authorization: `Bearer ${ANON_KEY}`,
  "Content-Type": "application/json",
};

// Default headers for Edge Function calls (no auth required, but anon key needed for routing)
export const functionHeaders = {
  "Content-Type": "application/json",
  Authorization: `Bearer ${ANON_KEY}`,
};

/**
 * Generate a unique source identifier for test isolation.
 * Each test run gets its own source prefix to avoid collisions.
 */
export function testSource(): string {
  return `test-${crypto.randomUUID().slice(0, 8)}`;
}

/**
 * Build a minimal valid job submission payload.
 */
export function makeJob(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    origin: {
      source: testSource(),
      reference: `ref-${crypto.randomUUID().slice(0, 8)}`,
    },
    title: "Integration Test Engineer",
    description: "This is a test job created by the integration test suite. It should be cleaned up after tests run.",
    ...overrides,
  };
}

/**
 * Submit a job via the Edge Function and return the response.
 */
export async function submitJob(
  body: Record<string, unknown>,
  headers: Record<string, string> = {},
): Promise<Response> {
  return fetch(`${FUNCTIONS_URL}/submit-job`, {
    method: "POST",
    headers: { ...functionHeaders, ...headers },
    body: JSON.stringify(body),
  });
}

/**
 * Create an API key via the Edge Function and return the response.
 */
export async function createApiKey(
  body: Record<string, unknown>,
): Promise<Response> {
  return fetch(`${FUNCTIONS_URL}/create-api-key`, {
    method: "POST",
    headers: functionHeaders,
    body: JSON.stringify(body),
  });
}

/**
 * Call a PostgREST RPC function.
 */
export async function rpc(
  fn: string,
  body: Record<string, unknown> = {},
): Promise<Response> {
  return fetch(`${REST_URL}/rpc/${fn}`, {
    method: "POST",
    headers: restHeaders,
    body: JSON.stringify(body),
  });
}

/**
 * Query jobs via PostgREST with optional query parameters.
 */
export async function queryJobs(params: string = ""): Promise<Response> {
  const sep = params ? "?" : "";
  return fetch(`${REST_URL}/jobs${sep}${params}`, {
    headers: restHeaders,
  });
}

/**
 * Reset rate limits using the service role.
 * Deletes all rate limit records to avoid interference between tests.
 */
export async function clearRateLimits(): Promise<void> {
  const res = await fetch(`${REST_URL}/rate_limits?id=gt.0`, {
    method: "DELETE",
    headers: {
      apikey: SERVICE_ROLE_KEY,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    },
  });
  await res.body?.cancel();
}

/**
 * Delete test jobs by source prefix using the service role.
 */
export async function cleanupJobs(sourcePrefix: string): Promise<void> {
  const res = await fetch(`${REST_URL}/jobs?source=like.${encodeURIComponent(sourcePrefix + "*")}`, {
    method: "DELETE",
    headers: {
      apikey: SERVICE_ROLE_KEY,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    },
  });
  await res.body?.cancel();
}

/**
 * Delete test API keys by name prefix using the service role.
 */
export async function cleanupApiKeys(namePrefix: string): Promise<void> {
  const res = await fetch(`${REST_URL}/api_keys?name=like.${encodeURIComponent(namePrefix + "*")}`, {
    method: "DELETE",
    headers: {
      apikey: SERVICE_ROLE_KEY,
      Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    },
  });
  await res.body?.cancel();
}
